---
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Ranil Fernando
#
# Install with:
#   ansible-galaxy collection install -r ansible/requirements.yml
#
# cisco.fmcansible is licensed GPL-3.0-or-later and is maintained by Cisco.
# See https://github.com/CiscoDevNet/FMCAnsible and the NOTICE file in this repo.
collections:
  - name: cisco.fmcansible
    version: ">=1.0.0,<2.0.0"
    source: https://galaxy.ansible.com
