---
- name: Get network objects
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get network objects
      cisco.fmcansible.fmc_configuration:
        operation: getAllNetworkObject
        path_params:
          domainUUID: "{{ domain_uuid }}"
        query_params:
          limit: 1000
        register_as: result
      vars:
        ansible_httpapi_host: "{{ fmc_hostname }}"
        ansible_user: "{{ fmc_username }}"
        ansible_httpapi_pass: "{{ fmc_password }}"
        ansible_httpapi_validate_certs: "{{ fmc_verify_ssl }}"

    - name: Show result
      debug:
        var: result
